return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"astro-language-server",
			"bash-language-server",
			"clang-format",
			"clangd",
			"goimports",
			"gopls",
			"lua-language-server",
			"nginx-config-formatter",
			"nginx-language-server",
			"oxfmt",
			"postgres-language-server",
			"prettierd",
			"rust-analyzer",
			"shellcheck",
			"sqlfmt",
			"stylua",
		},
		auto_update = false,
		run_on_start = true,
		start_delay = 3000,
		debounce_hours = 24,
	},
}
