return {
	"folke/snacks.nvim",
	priority = 1000,
	lazy = false,
	---@type snacks.Config
	opts = {
		animate = { enabled = true },
		bigfile = { enabled = true },
		bufdelete = { enabled = true },
		dashboard = { enabled = false },
		debug = { enabled = true },
		dim = { enabled = true },
		explorer = { enabled = false },
		git = { enabled = false },
		gitbrowse = { enabled = false },
		image = { enabled = false },
		indent = { enabled = false },
		input = { enabled = false },
		layout = { enabled = true },
		lazygit = { enabled = false },
		notifier = { enabled = false },
		notify = { enabled = false },
		picker = { enabled = false },
		profiler = { enabled = false },
		quickfile = { enabled = false },
		rename = { enabled = true },
		scope = { enabled = false },
		scratch = { enabled = false },
		scroll = { enabled = false },
		statuscolumn = { enabled = false },
		terminal = { enabled = false },
		toggle = { enabled = true },
		util = { enabled = true },
		win = { enabled = true },
		words = { enabled = false },
		zen = { enabled = true },
	},
}
